
from enum import Enum

class OxfordNanonisSignalNames(Enum):
    TIME = "Timestamp (ms)"
    MAGNETIC_FIELD = "Magnetic Field (T)"
    MAGNETIC_FIELD_SETPOINT = "Magnetic Field Setp. (T)"
    # He3 Probe Signal Names
    HE3_PROBE_TEMPERATURE = "Sample Space (K)"
    HE3_PROBE_TEMPERATURE_SETPOINT = "Sample Space Setp. (K)"
    # He4 Probe Default Signal Names
    HE4_VTI_TEMPERATURE = "He4 Sample Space (K)"
    HE4_VTI_TEMPERATURE_SETPOINT = "He4 Sample Space Setp. (K)"
    HE4_EXTRA_TEMP_SENSOR = "He4 Sample Temp (K)"
    HE4_EXTRA_TEMP_SENSOR_SETPOINT = "He4 Sample Temp Setp. (K)"
    # DC Inputs
    DC_INPUT1 = "Input 1 (V)"
    DC_INPUT2 = "Input 2 (V)"
    DC_INPUT3 = "Input 3 (V)"
    DC_INPUT4 = "Input 4 (V)"
    DC_INPUT5 = "Input 5 (V)"
    DC_INPUT6 = "Input 6 (V)"
    DC_INPUT7 = "Input 7 (V)"
    DC_INPUT8 = "Input 8 (V)"
    # DC Output
    DC_OUTPUT1 = "Output 1 (V)"
    DC_OUTPUT2 = "Output 2 (V)"
    DC_OUTPUT3 = "Output 3 (V)"
    DC_OUTPUT4 = "Output 4 (V)"
    DC_OUTPUT5 = "Output 5 (V)"
    DC_OUTPUT6 = "Output 6 (V)"
    DC_OUTPUT7 = "Output 7 (V)"
    DC_OUTPUT8 = "Output 8 (V)"
    # AC Inputs
    AC_INPUT1_X = "LI Demod 1 X (V)"
    AC_INPUT2_X = "LI Demod 2 X (V)"
    AC_INPUT3_X = "LI Demod 3 X (V)"
    AC_INPUT4_X = "LI Demod 4 X (V)"
    AC_INPUT5_X = "LI Demod 5 X (V)"
    AC_INPUT6_X = "LI Demod 6 X (V)"
    AC_INPUT7_X = "LI Demod 7 X (V)"
    AC_INPUT8_X = "LI Demod 8 X (V)"
    AC_INPUT1_Y = "LI Demod 1 Y (V)"
    AC_INPUT2_Y = "LI Demod 2 Y (V)"
    AC_INPUT3_Y = "LI Demod 3 Y (V)"
    AC_INPUT4_Y = "LI Demod 4 Y (V)"
    AC_INPUT5_Y = "LI Demod 5 Y (V)"
    AC_INPUT6_Y = "LI Demod 6 Y (V)"
    AC_INPUT7_Y = "LI Demod 7 Y (V)"
    AC_INPUT8_Y = "LI Demod 8 Y (V)"
    AC_INPUT1_R = "LI Demod 1 R (V)"
    AC_INPUT2_R = "LI Demod 2 R (V)"
    AC_INPUT3_R = "LI Demod 3 R (V)"
    AC_INPUT4_R = "LI Demod 4 R (V)"
    AC_INPUT5_R = "LI Demod 5 R (V)"
    AC_INPUT6_R = "LI Demod 6 R (V)"
    AC_INPUT7_R = "LI Demod 7 R (V)"
    AC_INPUT8_R = "LI Demod 8 R (V)"
    AC_INPUT1_PHASE = "LI Demod 1 Phi (deg)"
    AC_INPUT2_PHASE = "LI Demod 2 Phi (deg)"
    AC_INPUT3_PHASE = "LI Demod 3 Phi (deg)"
    AC_INPUT4_PHASE = "LI Demod 4 Phi (deg)"
    AC_INPUT5_PHASE = "LI Demod 5 Phi (deg)"
    AC_INPUT6_PHASE = "LI Demod 6 Phi (deg)"
    AC_INPUT7_PHASE = "LI Demod 7 Phi (deg)"
    AC_INPUT8_PHASE = "LI Demod 8 Phi (deg)"
    # AC Input Demodulation phase
    AC_DEMOD1_PHASE = "LI Demod 1 Ref (deg)"
    AC_DEMOD2_PHASE = "LI Demod 2 Ref (deg)"
    AC_DEMOD3_PHASE = "LI Demod 3 Ref (deg)"
    AC_DEMOD4_PHASE = "LI Demod 4 Ref (deg)"
    AC_DEMOD5_PHASE = "LI Demod 5 Ref (deg)"
    AC_DEMOD6_PHASE = "LI Demod 6 Ref (deg)"
    AC_DEMOD7_PHASE = "LI Demod 7 Ref (deg)"
    AC_DEMOD8_PHASE = "LI Demod 8 Ref (deg)"
    # AC Outputs
    AC_OUTPUT1_AMP = "LI Mod 1 Amp (V)"
    AC_OUTPUT2_AMP = "LI Mod 2 Amp (V)"
    AC_OUTPUT3_AMP = "LI Mod 3 Amp (V)"
    AC_OUTPUT4_AMP = "LI Mod 4 Amp (V)"
    AC_OUTPUT1_FREQ = "LI Frq Gen 1 (Hz)"
    AC_OUTPUT2_FREQ = "LI Frq Gen 2 (Hz)"
    AC_OUTPUT3_FREQ = "LI Frq Gen 3 (Hz)"
    AC_OUTPUT4_FREQ = "LI Frq Gen 4 (Hz)"
    
    